package com.perseverance.pvc.utils

import android.content.Context
import android.content.Intent
import android.util.Log
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInAccount
import com.google.android.gms.auth.api.signin.GoogleSignInClient
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.android.gms.common.api.ApiException
import com.google.android.gms.tasks.Task
import com.google.firebase.auth.AuthCredential
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider
import kotlinx.coroutines.tasks.await
import java.util.concurrent.CancellationException

class GoogleAuthClient(
    private val context: Context
) {
    private val auth: FirebaseAuth? = try { FirebaseAuth.getInstance() } catch (e: Exception) { null }
    
    // Get the current signed-in user or null
    fun getSignedInUser() = auth?.currentUser

    // Configure Google Sign In
    private fun getGoogleSignInClient(): GoogleSignInClient {
        // R.string.default_web_client_id is auto-generated by google-services plugin
        val gso = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestIdToken(context.getString(com.perseverance.pvc.R.string.default_web_client_id)) 
            .requestEmail()
            .build()

        return GoogleSignIn.getClient(context, gso)
    }

    // Launch the intent
    fun getSignInIntent(): Intent {
        return getGoogleSignInClient().signInIntent
    }

    // Sign out
    suspend fun signOut() {
        try {
            auth?.signOut()
            getGoogleSignInClient().signOut().await()
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }

    // Process the result from the activity
    suspend fun signInWithIntent(intent: Intent): SignInResult {
        if (auth == null) return SignInResult(null, "Authentication service unavailable (Offline Mode)")
        
        val task = GoogleSignIn.getSignedInAccountFromIntent(intent)
        try {
            val account = task.getResult(ApiException::class.java)
            val credential = GoogleAuthProvider.getCredential(account.idToken, null)
            val authResult = auth.signInWithCredential(credential).await()
            val user = authResult.user
            
            return SignInResult(
                data = user?.run {
                    UserData(
                        userId = uid,
                        username = displayName,
                        profilePictureUrl = photoUrl?.toString(),
                        email = email
                    )
                },
                errorMessage = null
            )
        } catch (e: ApiException) {
            e.printStackTrace()
            return SignInResult(data = null, errorMessage = e.message)
        } catch (e: Exception) {
            e.printStackTrace()
            if (e is CancellationException) throw e
            return SignInResult(data = null, errorMessage = e.message)
        }
    }
}

data class SignInResult(
    val data: UserData?,
    val errorMessage: String?
)

data class UserData(
    val userId: String,
    val username: String?,
    val profilePictureUrl: String?,
    val email: String?
)
